module.exports = function (grunt){
	grunt.initConfig({
		pkg:grunt.file.readJSON('package.json'),
		uglify:{
			buildall:{
				files:[{
					expand:true,
					src:"js/*.js",
					ext:'.min.js',
					dest:'dist'
				}]
			}
		},
		less:{
			main:{
				expand:true,
				src:"less/*.less",
				ext:'.css',
				dest:'dist'
			}
		},
		cssmin:{
			target:{
				files:[{
					expand:true,
					cwd:'dist/less',
					src:['*.css','!*.min.css'],
					ext:".min.css",
					dest:"dist/css"
				}]
			}
		},
		watch:{
			uglify:{
				files:['js/*.js'],
				tasks:['uglify'],
				options:{
					livereload:true
				}
			},
			less:{
				files:['less/*.less'],
				tasks:['less'],
				options:{
					livereload:true
				}
			},
			cssmin:{
				files:['dist/less/*.css'],
				tasks:['cssmin'],
				options:{
					options:true
				}
			}
		}
	});

	grunt.loadNpmTasks('grunt-contrib-uglify');
	grunt.loadNpmTasks('grunt-contrib-less');
	grunt.loadNpmTasks('grunt-contrib-cssmin');
	grunt.loadNpmTasks('grunt-contrib-watch');

	grunt.registerTask('default',['uglify','less','cssmin','watch']);
}